# Generated by Django 3.1.5 on 2021-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
