# Generated by Django 3.1.5 on 2021-02-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210222_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Album', 'Album'), ('Merchandise', 'Merchandise'), ('Photobook', 'Photobook'), ('Fan lights', 'Fan lights'), ('Accessories', 'Accessories')], default='Merchandise', max_length=50),
        ),
    ]
