# Generated by Django 3.1.5 on 2021-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20210308_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=150),
        ),
    ]
